#! /bin/bash -f
#
# Usage:
#
# Build the library    - build lib
# Build the test suite - build test
# Clean all binaries   - build clean
#

GCC='gcc'
OPT=''
DEB='-g'

build_lib() 
{
    rm -rf obj
    mkdir  obj

    src="src/*.c"
    for file in $src; do
        #
        # strip the .c extensions
        # strip the file path
        # put the base file in the obj directory
        #
        obj=${file%.*}     
        obj=${obj##*/}  
        obj="obj/"$obj  
            
        #
        # compile the files
        #
        $GCC $OPT $DEB -c $file -Iinclude -o $obj
    done
}

build_test()
{
    sh build clean
    sh build lib 
    
    src="test/*.c"
    for file in $src; do  
        #
        # strip the .c extionsions
        # compile the files
        #
        bin=${file%.*}
        $GCC $OPT $DEB -o $bin $file -Iinclude obj/*
    done
}

build_clean()
{
    rm -rf obj
    rm -f  include/*~
    rm -f  src/*~
    rm -f  test/*~
    
    bin="test/*"
    for file in $bin; do
        #
        # Remove non C files
        #
        ext=${file#*.}
        if [ "$ext" != "c" ] && [ "$ext" != "h" ] 
        then
            rm -f $file
        fi
    done
}

#
# the default target
#
target='lib'

if [ $# -lt 1 ]; then
    echo "Building default target: ${target}"
else
    target=$1
fi

if   [ "$target" = "lib" ]; then
    build_lib
elif [ "$target" = "test" ]; then
    build_test
elif [ "$target" = "clean" ]; then 
    build_clean
else   
    echo  "Unknown build target: ${target}"
fi



